### ISSUE TITLE
delilah-cisra recommendations for Sydney

### ISSUE THREAD

**Issue by delilah-cisra** [githubteacher/developers-dec-2016#11]
There are many things one can do in Sydney for fun and profit:
Macquarie Park is of course a well-known tourist mecca; and
Newtown and Crows Nest are good places to go for food.

**Comment by sammo2828** [comment]
Go to Macquarie Shops for shopping and food

**Comment by sammo2828** [comment]
Bondi Beach is a quiet beach less known by tourists
